site_name: Kusari Wiki
copyright: Copyright &copy; 2021 SwapDex
repo_url: https://github.com/kusari-network/kusari-docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3
theme:
    
  markdown_extensions:
  features:
    - navigation.instant
    - navigation.tracking
  name: material
  custom_dir: overrides
  logo: assets/swapdex-logo-circlewhite.png
  favicon: assets/swapdex-icon.png
  language: en
  
plugins:
  - search

extra:
  # Default mkdocs-material alternate links for untranslated pages
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
  alternate:
    - name: English
      link: ""
      lang: en
extra_css:
  - stylesheets/extra.css

 